nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:8080']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost:8080']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600
        '^/':
            allow_origin: [ '*' ]