controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

register:
    path: /api/register
    controller: App\Controller\RegistrationController::register
